# Changes here will be overwritten by Copier
AnswerStrategy: recommended
AuthorEmail: finn.rehnert@gmail.com
AuthorName: F4zination
Indentation: 2
JuliaMinVersion: 1.10.4
License: MIT
PackageName: GPX
PackageOwner: F4zination
PackageUUID: ee3a5d9d-6c02-5b26-ac74-3db00b4a5f5e
_commit: v0.8.0
_src_path: https://github.com/abelsiqueira/BestieTemplate.jl
